apiVersion: v1
kind: ConfigMap
metadata:
  name: flowfuse-npm-registry
data:
  config.yaml: |
    storage: /verdaccio/storage
    web:
      enable: false
    auth:
      flowfuse-auth:
        baseURL: http://172.17.0.1:3000
        adminSecret: secret
    packages:
      '@*/*':
        access: $authenticated
    log: { type: stdout, format: pretty, level: http }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowfuse-npm-registry
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowfuse-npm-registry
spec:
  selector:
    matchLabels:
      app: flowfuse-npm-registry
  template:
    metadata:
      labels:
        app: flowfuse-npm-registry
    spec:
      containers:
      - name: flowfuse-npm-registry
        image: containers.hardill.me.uk/flowfuse/flowfuse-npm-registry
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4873
        volumeMounts:
        - name: storage
          mountPath: /verdaccio/storage
        - name: config
          mountPath: /verdaccio/conf
      volumes:
      - name: config
        configMap:
          name: flowfuse-npm-registry
      - name: storage
        persistentVolumeClaim:
          claimName: flowfuse-npm-registry
---
apiVersion: v1
kind: Service
metadata:
  name: flowfuse-npm-registry
spec:
  type: ClusterIP
  selector:
    app: flowfuse-npm-registry
  ports:
  - port: 4873
    targetPort: 4873
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowfuse-npm-registry
  labels:
    name: flowfuse-npm-registry
spec:
  rules:
  - host: registry.flowforge.loc
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flowfuse-npm-registry
            port: 
              number: 4873

